apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: gateway-k8s
spec:
  selector:
    matchLabels:
      app: gateway-k8s
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: gateway-k8s
    spec:
      containers:
        - name: gateway-k8s
          image: gw-springboot:1.0
# Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8088 

