apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: quarkus-api-pn-k8s
spec:
  selector:
    matchLabels:
      app: quarkus-api-pn-k8s
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: quarkus-api-pn-k8s
    spec:
      containers:
        - name: quarkus-api-pn-k8s
          image: neogicel/quarkus-api-pn-jvm:2.0
# Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084 

