resources:
- name: quarkus-api-pn
  type: git
  source:
    uri: https://github.com/neogiciel/quarkus-api-pn.git

- name: docker-quarkus-api-pn-jvm
  type: docker-image
  source:
      repository: neogicel/quarkus-api-pn-jvm
      tag: '2.6'
      username: neogicel
      password: Patrice88$

jobs:
- name : package
  public: true
  serial: true
  plan:
  - get: quarkus-api-pn
    trigger: true
  - task: mvn-package
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: maven
          tag: 3.9.2-eclipse-temurin-20-alpine
      inputs:
        - name: quarkus-api-pn
      run:
        path: "mvn"
        args:
          - -f
          - quarkus-api-pn/pom.xml
          - clean
          - package
      outputs:
      - name: quarkus-api-pn-out
        path: quarkus-api-pn
  - put: docker-quarkus-api-pn-jvm
    params:
        build: .
        dockerfile: ~
        build_args:
          CONFIG_DIR: -t neogicel/quarkus-api-pn-jvm:1.0 .
