resources:
- name: quarkus-api-pn
  type: git
  source:
    uri: https://github.com/neogiciel/quarkus-api-pn.git

#- name: docker-quarkus-api-pn-jvm
#  type: docker-image
#  source:
#      repository: neogicel/quarkus-api-pn-jvm
#      tag: '2.6'
#      username: neogicel
#      password: Patrice88$

jobs:
- name : package
  public: true
  serial: true
  plan:
  - get: quarkus-api-pn
    trigger: true
  - task: mvn-package
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: maven
          tag: 3.9.2-eclipse-temurin-20-alpine
      inputs:
        - name: quarkus-api-pn
      outputs:
        - name: mvn-output
      run:
        path: /bin/bash
        args: 
          - quarkus-api-pn/ci/mvn-script.sh
      caches:
        - path: .m2
  
  - task: build-images
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
  #       repository: ubuntu
  #       repository: concourse/oci-build-task
  #       repository: rbekker87/build-tools
          #repository: amidos/dcind
          repository: karlkfi/concourse-dcind
      inputs:
      - name: mvn-output
      outputs:
      - name: workspace
      run:
        path: entrypoint.sh
        args:
          - bash
          - -ceux
          - |
            cd mvn-output
            docker build .
                
#        args:
#        - -c
#        - |
#          echo "test1"
#          systemctl start docker
#          echo "test2"
#          cd mvn-output
#          ls
#
#          docker build -f . -t neogicel/quarkus-api-pn-jvm:1.0 .
#docker build -f /src/main/docker/Dockerfile.jvm -t neogicel/quarkus-api-pn-jvm:1.0 .
#  - put: docker-remote-tunnel-image
#    params:
#      build: workspace
